require("prototypes.techs")
require("prototypes.mining")
require("prototypes.furnace")
require("prototypes.energy")
require("prototypes.assemblers")
require("prototypes.steel_chest")
require("prototypes.inserters")
require("prototypes.train_stop")
